name: Build Go-IMN

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      
    - name: Build Go-IMN
      run: make gimn.tar.gz
    - name: Check Build
      run: ls -al build/gimn.tar.gz
